### ISSUE TITLE
US5: Implement the existing emoji button’s functionality

### ISSUE THREAD

**Issue by Akshra-school** [CMU-313/nodebb-f24-cmu-secure#2]

**Comment by Akshra-school** [comment]
**Estimated Effort**: Low

**Acceptance Criteria**:
- Clicking the emoji button in the chat message field should display an emoji menu
- User should be able to select any emoji from the emoji menu

**Comment by tanoctavius** [comment]
This was initially meant to be done in Sprint 2, but after reevaluation with the team, we decided that it could not be pursued with the manpower and time available. We instead decided to only concentrate on the US1, and US4 within the second sprint.
