### ISSUE TITLE
US5: Add logic for inserting emoji into chat message field upon selection

### ISSUE THREAD

**Issue by Akshra-school** [CMU-313/nodebb-f24-cmu-secure#3]

**Comment by Akshra-school** [comment]
**Estimated Effort**: Low

**Acceptance Criteria**:
- Emoji should be inserted into the chat message field after any current text
- Emojis in the sent message should be visible to recipients

**Comment by tanoctavius** [comment]
This was initially meant to be done in Sprint 2, but after reevaluation with the team, we decided that it could not be pursued with the manpower and time available. We instead decided to only concentrate on the US1, and US4 within the second sprint.
