### ISSUE TITLE
US6: Implement backend logic to store information about selected emojis, specifically the associated user and message

### ISSUE THREAD

**Issue by Akshra-school** [CMU-313/nodebb-f24-cmu-secure#7]

**Comment by Akshra-school** [comment]
**Estimated Effort**: Moderate

**Acceptance Criteria**:
- When one clicks on an emoji reaction under the message, you should be able to see who gave what emoji reaction to any message

**Comment by tanoctavius** [comment]
This was initially meant to be done in Sprint 2, but after reevaluation with the team, we decided that it could not be pursued with the manpower and time available. We instead decided to only concentrate on the US1, and US4 within the second sprint.
