### ISSUE TITLE
US6: Add logic for removing emoji reaction from message

### ISSUE THREAD

**Issue by Akshra-school** [CMU-313/nodebb-f24-cmu-secure#8]

**Comment by Akshra-school** [comment]
**Estimated Effort**: Moderate

**Acceptance Criteria**:
- Users should be able to click on an emoji that they reacted with and select whether they want to remove the reaction or not
- Only an user who selected the emoji reaction should be able to remove it, you should not be able remove other people’s reactions

**Comment by tanoctavius** [comment]
This was initially meant to be done in Sprint 2, but after reevaluation with the team, we decided that it could not be pursued with the manpower and time available. We instead decided to only concentrate on the US1, and US4 within the second sprint.
